// SPEC-E section 2 - Vera rule table v1: 35 rules (8 term + 10 claim +
// 5 consent + 7 platform + 5 brand), plus per-person VERA-DNS-* BLOCK rules
// compiled from fact-file do_not_say[] at evaluation time (engine.mjs).
// Patterns are stored as source strings; the engine compiles a fresh RegExp
// per evaluation so global-flag lastIndex state never leaks. All patterns
// case-insensitive unless noted. `check` names live in checks.mjs.
export const RULESET_VERSION = 1;

export const MONEY_SRC = String.raw`\$\s?\d[\d,.]*\s*(?:k|m|mm|bn?|thousand|million|billion)?`;

export const RULES = [
  // ------- Class 1: term (BLOCK regex/term rules) -------
  { id: 'VERA-T01', cls: 'term', severity: 'block',
    pattern: String.raw`\bAUM\b|\bassets\s+under\s+management\b`,
    message: 'AUM is a prohibited firm claim. Centurion does not manage assets.',
    fix: "Reframe as principals' lifetime transactions advised/closed, or remove the figure." },
  { id: 'VERA-T02', cls: 'term', severity: 'block',
    pattern: String.raw`\b(raised|raising|we've\s+raised)\s+(over\s+|more\s+than\s+|nearly\s+|~\s*)?\$?\s*[0-9]`,
    message: '"raised $X" is a prohibited capital-raise claim.',
    fix: 'Reframe as "advised on transactions of..." or "term sheets secured...".' },
  { id: 'VERA-T03', cls: 'term', severity: 'block',
    pattern: String.raw`\$\s*2\s*(B\b|Bn\b|billion\b)`,
    message: '"$2B" as a firm figure is off the fact base.',
    fix: "Remove, or replace with a registry-matched figure in principals'-lifetime framing." },
  { id: 'VERA-T04', cls: 'term', severity: 'block', check: 'founding_year',
    message: 'Wrong founding year. Centurion Financial was founded 2021 (F-001).',
    fix: 'State "founded 2021" or omit.' },
  { id: 'VERA-T05', cls: 'term', severity: 'block',
    pattern: String.raw`\bSum\s+Capital\b`,
    message: '"Sum Capital" must not be named until the Singapore JV signs (F-007).',
    fix: 'Remove the name; "a Singapore partner" is acceptable if needed.' },
  { id: 'VERA-T06', cls: 'term', severity: 'block',
    pattern: String.raw`\bclosed\s+capital\b|\bcapital\s+closed\b`,
    message: 'Prohibited framing (F-004).',
    fix: 'Use "term sheets".' },
  { id: 'VERA-T07', cls: 'term', severity: 'block',
    pattern: String.raw`\bHead\s+Underwriter\b`,
    message: '"Head Underwriter" is a proposed restructure function, not a current title (F-006). Tricia Littell is COO.',
    fix: "Use the person's fact-file title." },
  { id: 'VERA-T08', cls: 'term', severity: 'block',
    pattern: String.raw`\bguaranteed?\s+(returns?|yields?|funding|approval|close|outcome)\b|\brisk[-\s]?free\b`,
    message: 'Guarantee / risk-free language is a legal-claims violation and a platform-ToS misleading claim.',
    fix: 'State process and track record; never outcomes.' },

  // ------- Class 2: claim (evidence-required rules) -------
  { id: 'VERA-C01', cls: 'claim', severity: 'block', check: 'numeric_claim_whitelist',
    message: 'Every $ figure and % must match a registry fact / approved_claim or carry a fact-file citation. Unmatched figure found.',
    fix: 'Cite the approved_claim id, replace with the whitelisted figure, or delete.' },
  { id: 'VERA-C02', cls: 'claim', severity: 'flag', check: 'count_claim_whitelist',
    message: "Count claims (transactions, funders, years...) must match the fact registry or the subject's approved_claims.",
    fix: 'Cite or correct the count.' },
  { id: 'VERA-C03', cls: 'claim', severity: 'block', check: 'lifetime_framing',
    message: 'Large aggregates may only appear as "principals\' lifetime transactions advised/closed" (F-002).',
    fix: 'Add the framing or remove the figure.' },
  { id: 'VERA-C04', cls: 'claim', severity: 'block', check: 'pipeline_headline',
    message: 'Deal-flow headline must be the current active pipeline value from the live query - never a lifetime aggregate (F-003).',
    fix: "Bind the number to the pipeline query or reframe as principals'-lifetime." },
  { id: 'VERA-C05', cls: 'claim', severity: 'block', check: 'employer_claims',
    message: "Employer/engagement claim not in the person's verified list (F-008 for Ashton).",
    fix: 'Remove the org or verify it into the fact-file first.' },
  { id: 'VERA-C06', cls: 'claim', severity: 'block', check: 'education_claims',
    message: 'Education claim not in the fact-file.',
    fix: 'Match the fact-file entry exactly or remove.' },
  { id: 'VERA-C07', cls: 'claim', severity: 'block', check: 'title_claims',
    message: "Title does not match the person's approved title.",
    fix: 'Use the fact-file title verbatim.' },
  { id: 'VERA-C08', cls: 'claim', severity: 'block', check: 'powered_labs_one_liner',
    message: 'Powered Labs is one line only (F-005).',
    fix: 'Use: "Powered Labs (2010-2018, exited)."' },
  { id: 'VERA-C09', cls: 'claim', severity: 'flag',
    pattern: String.raw`\b(largest|leading|premier|best[-\s]in[-\s]class|#\s?1|top[-\s]?tier|unmatched|unrivaled)\b`,
    message: 'Superlative needs evidence or removal (also a platform misleading-claims risk).',
    fix: 'Replace with a specific, citable fact.' },
  { id: 'VERA-C10', cls: 'claim', severity: 'block', check: 'real_dates',
    message: 'Publication and event dates must be real - never backdated (F-010; Wayback makes forgery detectable).',
    fix: 'Use the true date or do not publish.' },

  // ------- Class 3: consent rules -------
  { id: 'VERA-N01', cls: 'consent', severity: 'block', check: 'client_naming',
    message: 'Client named without consent flag (F-009).',
    fix: 'Anonymize ("a Southeast sponsor") and size-band.' },
  { id: 'VERA-N02', cls: 'consent', severity: 'block', check: 'size_banding',
    message: 'Exact client-deal size without consent.',
    fix: 'Replace with the size band ($1-5M, $5-15M, $15-50M, $50M+).' },
  { id: 'VERA-N03', cls: 'consent', severity: 'block', check: 'subject_signed_off',
    message: 'No HERALD agent publishes for an unsigned person (SPEC-I hard gate, alias VERA-G01).',
    fix: 'Hold as draft until sign-off completes.' },
  { id: 'VERA-N04', cls: 'consent', severity: 'block', check: 'delegation_capability',
    message: "Action exceeds the person's delegation grant or tier.",
    fix: 'Route to their approval queue instead.' },
  { id: 'VERA-N05', cls: 'consent', severity: 'block', check: 'third_party_pii',
    message: 'Third-party PII in public content.',
    fix: 'Remove the personal contact detail.' },

  // ------- Class 4: platform (ToS) rules -------
  { id: 'VERA-P01', cls: 'platform', severity: 'block',
    pattern: String.raw`\bengagement\s+pods?\b|\bfollow[-\s]?(4|for)[-\s]?follow\b|\blike[-\s]?(4|for)[-\s]?like\b|\bcomment\s+(exchange|swap|pod)\b|\bpod\s+squad\b`,
    message: 'Engagement-pod / reciprocal-engagement language violates platform ToS and the P0 "never look botted" invariant.',
    fix: 'Delete; engagement must be organic and warm.' },
  { id: 'VERA-P02', cls: 'platform', severity: 'flag',
    pattern: String.raw`\byou\s+won'?t\s+believe\b|\bthis\s+one\s+(trick|secret)\b|\bbanks\s+hate\b|\bsecret\s+(they|banks|lenders)\b`,
    message: 'Misleading/clickbait framing (platform misleading-claims policy + brand).',
    fix: 'Rewrite the hook honestly.' },
  { id: 'VERA-P03', cls: 'platform', severity: 'block', check: 'promo_disclosure',
    message: 'Material-connection promotion without disclosure (FTC + platform rules).',
    fix: 'Add the disclosure line (#ad / "client of Centurion" / "we advise X").' },
  { id: 'VERA-P04', cls: 'platform', severity: 'block', flags: 'gis',
    pattern: String.raw`\binvest\s+now\b|\bDM\s+(me|us)\s+to\s+invest\b|\bofferings?\b.{0,40}\bsecurit(y|ies)\b|\baccredited\s+investors?\s+only\b.{0,60}\bDM\b`,
    message: 'Public investment solicitation language - legal + platform risk for a financial-services page.',
    fix: "Route capital conversations to the site's compliant channels; never solicit in-feed." },
  { id: 'VERA-P05', cls: 'platform', severity: 'block', check: 'rate_caps',
    message: 'Daily cap reached for this action class.',
    fix: 'No fix - the run halts and reports.' },
  { id: 'VERA-P06', cls: 'platform', severity: 'block', check: 'duplicate_content',
    message: 'Duplicate engagement text looks automated (spam policy).',
    fix: 'Vary the copy or skip the target.' },
  { id: 'VERA-P07', cls: 'platform', severity: 'flag', check: 'stuffing',
    message: 'Hashtag/mention stuffing reads as spam.',
    fix: 'Trim to <= 5 hashtags, mention only relevant connections.' },

  // ------- Class 5: brand / tone rules -------
  { id: 'VERA-B01', cls: 'brand', severity: 'flag', flags: 'giu',
    pattern: String.raw`\b(guru|ninja|rockstar|game[-\s]?changer|crush(ing|ed)\s+it|to\s+the\s+moon|hustle\s+hard)\b|\u{1F680}`,
    message: 'Hype lexicon is off the Centurion voice (confident, non-promissory, institutional).',
    fix: 'Rewrite in brand voice.' },
  { id: 'VERA-B02', cls: 'brand', severity: 'block',
    pattern: String.raw`\bwill\s+(double|triple|10x)\b|\b10x\s+your\b|\bget\s+funded\s+in\s+\d+\s+(hours?|days?)\s+guaranteed\b`,
    message: 'Promissory performance language.',
    fix: 'Describe process and history, never promised outcomes.' },
  { id: 'VERA-B03', cls: 'brand', severity: 'flag', check: 'sensitive_topics',
    message: 'Sensitive/derogatory topic - human must review.',
    fix: "Usually: don't engage." },
  { id: 'VERA-B04', cls: 'brand', severity: 'flag',
    pattern: String.raw`\bcenturian\b|\bcenturion\s+finance\b(?!\s*(corp|llc))|centurionfinancial(?!\.com)\b`,
    message: 'Brand misspelling / wrong entity name.',
    fix: '"Centurion Financial"; site is centurionfinancial.com (F-011).' },
  { id: 'VERA-B05', cls: 'brand', severity: 'flag', check: 'voice_score', llm: true,
    message: "Draft doesn't sound like the person's approved voice.",
    fix: 'Nico redrafts in voice.' },
];
